Add Ionicons for mobile phone and phone/email feedback (for contact icons)
reonomy/styles pull request #26
Opened 2020-11-13 22:40 UTC by igor-p

Ticket: [OA-368](https://reonomy.atlassian.net/browse/OA-368)

I needed to update 2 icons in the property owner tab contact area. `<IconPhonePortraitSolid>` appears on the left side of a phone number that's identified as a cellphone. And `<IconStarHalfSolid>` replaces the "thumbs up/down" icon that opens the phone/email feedback popover.

I'm marking this as `wip` as I'm not yet able import these icons into the `/example/` directory to ensure that they were added

2020-11-16 21:01 UTC, herrethan commented on src/ionicons/solidIcons/IconStarHalfSolid.tsx
> +    </SvgIcon>
icons like this should have `stroke="currentColor"` set as a `SvgIcon` attribute instead. (see ArrowIcons.tsx)

2020-11-16 21:02 UTC, herrethan commented on src/ionicons/solidIcons/IconPhonePortraitSolid.tsx
> +        fill="currentColor"
shouldn't need `fill="currentColor"` on these paths

2020-11-16 21:02 UTC, herrethan commented on src/ionicons/solidIcons/IconPhonePortraitSolid.tsx
> +    <SvgIcon viewBox="0 0 14 24" fill="none" {...props}>
view box should _always_ be `0 0 24 24`

2020-11-16 21:03 UTC, herrethan requested changes
Can we also add the Outline versions of both these icons?

2020-11-16 21:04 UTC, herrethan commented on .gitignore
> +*.iml
nit: newline

2020-11-17 18:34 UTC, igor-p commented on src/ionicons/solidIcons/IconPhonePortraitSolid.tsx
> +    <SvgIcon viewBox="0 0 14 24" fill="none" {...props}>
Fixed in a4772c82926b9e8dbaded63a4be20c5305957586

2020-11-17 18:35 UTC, igor-p commented
> Can we also add the Outline versions of both these icons?

I added the outline version of `PhonePortrait`, but the star icon is the same in both solid and outline variants.

2020-11-17 18:49 UTC, herrethan commented
> I added the outline version of `PhonePortrait`, but the star icon is the same in both solid and outline variants.
That's fine, I believe for the most part the same solid/outline icons have been duplicated thus far, just for consistency. But probably unnecessary.

2020-11-17 18:51 UTC, herrethan approved these changes

2020-11-17 19:03 UTC, igor-p commented
> > I added the outline version of `PhonePortrait`, but the star icon is the same in both solid and outline variants.
> 
> That's fine, I believe for the most part the same solid/outline icons have been duplicated thus far, just for consistency. But probably unnecessary.

Ah, that makes sense. Probably good to throw in the alternate version in any case

2020-11-17 20:20 UTC, herrethan approved these changes

2020-11-17 20:28 UTC, merged